---

namespace: kubealex

name: eda

version: 1.0.6

readme: README.md

authors:
  - Alessandro Rossi <al.rossi87@gmail.com>

description: Event Driven Automation

license_file: 'LICENSE'

tags:
  - eda
  - ansible
  - events
  - mqtt
  - infrastructure

# dependencies:

repository: https://github.com/kubealex/kubealex.eda

documentation: https://github.com/kubealex/kubealex.eda.git

issues: https://github.com/kubealex/kubealex.eda.git/issues

build_ignore: []
